import Room from "./room";

let roomList = [];

/**
 * Add a new Room object into the arraylist of Room
 * @param {String} player The indentifier of player, generated by getUniqueID method from auth.js
 * @param {String} mode define single mode or multiple mode of the room. 'single'/'Multiple'
 * @param {[Room]} roomList The room list initilized by server
 */
export const createRoom = (player, mode = "single") => {
  const room = new Room(mode);
  room.join(player);
  roomList.push(room);
  return room;
};

/**
 * Search for empty room in the roomList and join automatically when there is available position
 * For multiplayer mode use only
 * @param {String} player The indentifier of player, generated by getUniqueID method from auth.js
 * @param {[{}]} roomList The room list initilized by server
 */
export const joinOrCreateMultipleGame = player => {
  const room = roomList.find(r => !r.isFull());
  if (!room) {
    return createRoom(player, "multiple", roomList);
  }
  room.join(player);
};

/**
 * Remove Room object from the list when there is no player in the room.
 * @param {*} roomList
 * @param {*} room
 */
export const removeEmptyRoom = room => {
  const index = roomList.indexOf(room);
  if (roomList(index).isEmpty()) roomList.splice(index, 1);
};

/**
 * Get player board by sessionId
 * @param {[]} roomList
 * @param {string} sessionId
 * @returns the corresponding board object
 */
export const getBoardBySessionID = sessionId => {
  const room = getRoomWithSessionID(sessionId);
  return room.getBoardBySessionID(sessionId);
};

export const getRoomWithSessionID = sessionId => {
  return roomList.find(room => room.players.some(p => p.id === sessionId));
};
